# shops-registry-sync.ps1 - regenerate ~/.claude/shops-registry.json from the
# markdown table in ~/.claude/shops-registry.md (the human-authoritative source).
# Run this after adding/editing a shop row in the .md so the hooks (which read the
# .json) stay in sync. Normalizes folder_root (lowercase, forward slash, no trailing
# slash) and converts <TODO>/backtick placeholders to empty strings. ASCII output.
$ErrorActionPreference = 'Stop'
$md = Join-Path $env:USERPROFILE '.claude/shops-registry.md'
$jsonPath = Join-Path $env:USERPROFILE '.claude/shops-registry.json'
if (-not (Test-Path -LiteralPath $md)) { Write-Error "missing $md"; exit 1 }

$cols = @('shop_name','folder_root','store_handle','myshopify_domain','currency','niche','token_path','creds_path','app_name','write_policy','status')
$lines = Get-Content -LiteralPath $md
$inTable = $false
$shops = @()
foreach ($line in $lines) {
  $t = $line.Trim()
  if ($t -notmatch '^\|') { if ($inTable) { break } else { continue } }
  # header row -> start table; separator row -> skip
  if ($t -match 'shop_name' -and $t -match 'folder_root') { $inTable = $true; continue }
  if (-not $inTable) { continue }
  if ($t -match '^\|[\s\-:|]+\|$') { continue }   # |---|---| separator
  $cells = $t.Trim('|').Split('|') | ForEach-Object { $_.Trim().Trim('`').Trim() }
  if ($cells.Count -lt $cols.Count) { continue }
  $o = [ordered]@{}
  for ($i = 0; $i -lt $cols.Count; $i++) {
    $v = [string]$cells[$i]
    if ($v -match '^<TODO>(\.myshopify\.com)?$') { $v = '' }   # placeholder -> empty
    if ($cols[$i] -eq 'folder_root') { $v = ($v -replace '\\','/').ToLower().TrimEnd('/') }
    $o[$cols[$i]] = $v
  }
  $shops += [pscustomobject]$o
}
if ($shops.Count -eq 0) { Write-Error "no shop rows parsed from $md (check the table header has shop_name/folder_root)"; exit 1 }

# integrity: no duplicate folder_root / handle / domain / token_path
foreach ($field in 'folder_root','store_handle','myshopify_domain','token_path') {
  $vals = @($shops | ForEach-Object { [string]$_.$field } | Where-Object { $_ -ne '' })
  $dupes = @($vals | Group-Object | Where-Object { $_.Count -gt 1 } | ForEach-Object { $_.Name })
  if ($dupes.Count -gt 0) { Write-Error ("REGISTRY INVARIANT BROKEN: duplicate " + $field + " -> " + ($dupes -join ', ')); exit 1 }
}

$obj = [ordered]@{
  _comment = 'Machine mirror of shops-registry.md - GENERATED by shops-registry-sync.ps1. Edit the .md table then re-run the sync; do not hand-edit this file. Read by shop-identity-guard / shop-token-identity-block / shops-whoami / shops-banner. folder_root normalized lowercase + forward-slash, no trailing slash.'
  shops = $shops
}
$obj | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding ASCII
Write-Output ("synced " + $shops.Count + " shops -> " + $jsonPath)
foreach ($s in $shops) { Write-Output ("  - " + $s.shop_name + " [" + $s.write_policy + "/" + $s.status + "] " + $s.folder_root) }
